
Sun Azimuth Angle (deg.)
Sun Zenith Angle (deg.)
Air Mass (#)
Extraterrestial Irradiance (W/m2)
    Horizontal Global Irradiance (W/m2)
Normal beam irradiance (W/m2)
Horizontal beam irradiance (W/m2)
    Horizontal diffuse irradiance (W/m2)
Ambient Temperature (deg. C)
Wind Velocity (m/s)
Albedo (Unitless)
Tracker Slope (deg.)
Tracker Azimuth (deg.)
Collector Surface Slope (deg.)
Collector Surface Azimuth (deg.)
Rotation Angle (deg.)
Incidence Angle (deg.)

    Global Irradiance in Array Plane (W/m2)
Beam Irradiance in Array Plane (W/m2)
Diffuse Irradiance in Array Plane (W/m2)
Ground Reflected Irradiance in Array Plane (W/m2)

    Horizon Shading Loss for Global (W/m2)
Horizon Shading Loss for Beam (W/m2)
Horizon Shading Loss for Diffuse (W/m2)
Horizon Shading Loss for Ground Reflected (W/m2)

Profile Angle (deg.)
Near Shading Factor on Global (Unitless)
Near Shading Factor on Beam (Unitless)
Near Shading Factor on  Diffuse (Unitless)
Near Shading Factor on Ground Reflected (Unitless)
    Near Shading Loss for Global (W/m2)
Near Shading Loss for Beam (W/m2)
Near Shading Loss for Diffuse (W/m2)
Near Shading Loss for Ground Reflected (W/m2)

Global POA Irradiance Corrected for Shading (W/m2)

IAM Factor on Global (Unitless)
IAM Factor on Beam (Unitless)
IAM Factor on  Diffuse (Unitless)
IAM Factor on Ground Reflected (Unitless)
    Incidence Loss for Global (W/m2)
Incidence Loss for Beam (W/m2)
Incidence Loss for Diffuse (W/m2)
Incidence Loss for Ground Reflected (W/m2)
Global POA Irradiance Corrected for Incidence (W/m2)

    Soiling Loss (W/m2)

Inter-row Albedo (Unitless)
Global Irradiance on Ground (W/m2)
Back IAM Factor on Beam (Unitless)
Back IAM Factor on Diffuse (Unitless)
Beam Irradiance in Array Back (W/m2)

Effective Global Irradiance in Array Back (W/m2)
Effective Beam Irradiance in Array Back (W/m2)
Effective Diffuse Irradiance in Array Back (W/m2)
Effective Ground Reflected Irradiance in Array Back (W/m2)
Effective Front Reflected Irradiance in Array Back (W/m2)
Effective Global Irradiance on Back Cell Row 1 (W/m2)
Effective Global Irradiance on Back Cell Row 2 (W/m2)
Effective Global Irradiance on Back Cell Row 3 (W/m2)
Effective Global Irradiance on Back Cell Row 4 (W/m2)
Effective Global Irradiance on Back Cell Row 5 (W/m2)
Effective Global Irradiance on Back Cell Row 6 (W/m2)
Inhomogeneity of Global Irradiance in Array Back (Unitless)
Bifacial Gain (W/m2)
Spectral Loss (W/m2)
    Effective Global Irradiance in Array Plane (W/m2)
Radiation Available for Power Conversion (W/m2)
Measured Module Temperature (deg. C)
Calculated Module Temperature (deg. C)
Difference between Module and Ambient Temp. (deg. C)
Array Nominal Power (kW)
Energy Loss Due To Temperature (kW)
Energy Loss Due To Irradiance Level (kW)
Module Quality Loss (kW)
Module LID (kW)
Module ageing (kW)
Modules Array Mismatch Loss (kW)
DC Wiring Loss (kW)
SubArray 1 PV. Voltage (V)
SubArray 1 PV. Current (A)
SubArray 1 PV. Power (kW)
Effective Voltage at the Output of the Array (V)
Effective Current at the Output of the Array (A)
Virtual Energy Available to Inverter (kW)
Inverter Loss Due to Low Voltage Threshold (kW)
Inverter Loss Due to High Voltage Threshold (kW)
Inverter Loss Due to Low Power Threshold  (kW)
Inverter Loss Due to High Power Threshold (Clipping) (kW)
Actual Energy Available to Inverter (kW)
DC to AC Conversion Loss (kW)
SubArray 1 Inv. 3-Phase Power (W)
Available Power at Inverter Output (kW)
AC Ohmic Loss (kW)
Main Transformer Loss (day-time) (kW)
Main Transformer Loss (night-time) (kW)
Power Injected into Grid (kW)
Energy Injected into Grid (kWh)
PV Array Efficiency (%)
Inverter Efficiency  (%)
AC-side Efficiency (%)
Overall System Efficiency (%)
